/**
 * The MIT License (MIT)
 *
 * Copyright (c) 2018-2019 Erik Moqvist
 *
 * Permission is hereby granted, free of charge, to any person
 * obtaining a copy of this software and associated documentation
 * files (the "Software"), to deal in the Software without
 * restriction, including without limitation the rights to use, copy,
 * modify, merge, publish, distribute, sublicense, and/or sell copies
 * of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be
 * included in all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
 * NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS
 * BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN
 * ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN
 * CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

/**
 * This file was generated by cantools version 35.3.0 Fri Dec  8 21:19:10 2023.
 */

#include <string.h>

#include "flash.h"

static inline uint8_t pack_left_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_left_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value << shift) & mask);
}

static inline uint8_t pack_right_shift_u32(
    uint32_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint8_t pack_right_shift_u64(
    uint64_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value >> shift) & mask);
}

static inline uint32_t unpack_left_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) << shift);
}

static inline uint64_t unpack_left_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) << shift);
}

static inline uint8_t unpack_right_shift_u8(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint8_t)((uint8_t)(value & mask) >> shift);
}

static inline uint32_t unpack_right_shift_u32(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint32_t)((uint32_t)(value & mask) >> shift);
}

static inline uint64_t unpack_right_shift_u64(
    uint8_t value,
    uint8_t shift,
    uint8_t mask)
{
    return (uint64_t)((uint64_t)(value & mask) >> shift);
}

int flash_system_status_pack(
    uint8_t *dst_p,
    const struct flash_system_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u8(src_p->goto_app, 0u, 0x01u);
    dst_p[0] |= pack_left_shift_u8(src_p->goto_iap, 1u, 0x02u);

    return (8);
}

int flash_system_status_unpack(
    struct flash_system_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->goto_app = unpack_right_shift_u8(src_p[0], 0u, 0x01u);
    dst_p->goto_iap = unpack_right_shift_u8(src_p[0], 1u, 0x02u);

    return (0);
}

uint8_t flash_system_status_goto_app_encode(double value)
{
    return (uint8_t)(value);
}

double flash_system_status_goto_app_decode(uint8_t value)
{
    return ((double)value);
}

bool flash_system_status_goto_app_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

uint8_t flash_system_status_goto_iap_encode(double value)
{
    return (uint8_t)(value);
}

double flash_system_status_goto_iap_decode(uint8_t value)
{
    return ((double)value);
}

bool flash_system_status_goto_iap_is_in_range(uint8_t value)
{
    return (value <= 1u);
}

int flash_dcu_status_pack(
    uint8_t *dst_p,
    const struct flash_dcu_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->status, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->status, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->status, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->status, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->status, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->status, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->status, 56u, 0xffu);

    return (8);
}

int flash_dcu_status_unpack(
    struct flash_dcu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t flash_dcu_status_status_encode(double value)
{
    return (uint64_t)(value);
}

double flash_dcu_status_status_decode(uint64_t value)
{
    return ((double)value);
}

bool flash_dcu_status_status_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_write_req_pack(
    uint8_t *dst_p,
    const struct flash_dcu_write_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dcu_write_req_unpack(
    struct flash_dcu_write_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_write_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_write_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_write_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dcu_write_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_write_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_write_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_write_res_pack(
    uint8_t *dst_p,
    const struct flash_dcu_write_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dcu_write_res_unpack(
    struct flash_dcu_write_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_write_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_write_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_write_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dcu_write_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_write_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_write_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_read_req_pack(
    uint8_t *dst_p,
    const struct flash_dcu_read_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dcu_read_req_unpack(
    struct flash_dcu_read_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_read_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_read_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_read_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dcu_read_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_read_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_read_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_read_res_pack(
    uint8_t *dst_p,
    const struct flash_dcu_read_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dcu_read_res_unpack(
    struct flash_dcu_read_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_read_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_read_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_read_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dcu_read_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_read_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_read_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_erase_req_pack(
    uint8_t *dst_p,
    const struct flash_dcu_erase_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_dcu_erase_req_unpack(
    struct flash_dcu_erase_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_erase_req_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_erase_req_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_erase_req_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dcu_erase_res_pack(
    uint8_t *dst_p,
    const struct flash_dcu_erase_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_dcu_erase_res_unpack(
    struct flash_dcu_erase_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_dcu_erase_res_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dcu_erase_res_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dcu_erase_res_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_status_pack(
    uint8_t *dst_p,
    const struct flash_ecu_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->status, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->status, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->status, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->status, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->status, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->status, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->status, 56u, 0xffu);

    return (8);
}

int flash_ecu_status_unpack(
    struct flash_ecu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t flash_ecu_status_status_encode(double value)
{
    return (uint64_t)(value);
}

double flash_ecu_status_status_decode(uint64_t value)
{
    return ((double)value);
}

bool flash_ecu_status_status_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_write_req_pack(
    uint8_t *dst_p,
    const struct flash_ecu_write_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ecu_write_req_unpack(
    struct flash_ecu_write_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_write_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_write_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_write_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ecu_write_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_write_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_write_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_write_res_pack(
    uint8_t *dst_p,
    const struct flash_ecu_write_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ecu_write_res_unpack(
    struct flash_ecu_write_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_write_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_write_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_write_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ecu_write_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_write_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_write_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_read_req_pack(
    uint8_t *dst_p,
    const struct flash_ecu_read_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ecu_read_req_unpack(
    struct flash_ecu_read_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_read_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_read_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_read_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ecu_read_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_read_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_read_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_read_res_pack(
    uint8_t *dst_p,
    const struct flash_ecu_read_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ecu_read_res_unpack(
    struct flash_ecu_read_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_read_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_read_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_read_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ecu_read_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_read_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_read_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_erase_req_pack(
    uint8_t *dst_p,
    const struct flash_ecu_erase_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ecu_erase_req_unpack(
    struct flash_ecu_erase_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_erase_req_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_erase_req_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_erase_req_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ecu_erase_res_pack(
    uint8_t *dst_p,
    const struct flash_ecu_erase_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ecu_erase_res_unpack(
    struct flash_ecu_erase_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ecu_erase_res_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ecu_erase_res_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ecu_erase_res_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_status_pack(
    uint8_t *dst_p,
    const struct flash_ccu_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->status, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->status, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->status, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->status, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->status, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->status, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->status, 56u, 0xffu);

    return (8);
}

int flash_ccu_status_unpack(
    struct flash_ccu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t flash_ccu_status_status_encode(double value)
{
    return (uint64_t)(value);
}

double flash_ccu_status_status_decode(uint64_t value)
{
    return ((double)value);
}

bool flash_ccu_status_status_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_write_req_pack(
    uint8_t *dst_p,
    const struct flash_ccu_write_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ccu_write_req_unpack(
    struct flash_ccu_write_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_write_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_write_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_write_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ccu_write_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_write_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_write_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_write_res_pack(
    uint8_t *dst_p,
    const struct flash_ccu_write_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ccu_write_res_unpack(
    struct flash_ccu_write_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_write_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_write_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_write_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ccu_write_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_write_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_write_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_read_req_pack(
    uint8_t *dst_p,
    const struct flash_ccu_read_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ccu_read_req_unpack(
    struct flash_ccu_read_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_read_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_read_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_read_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ccu_read_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_read_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_read_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_read_res_pack(
    uint8_t *dst_p,
    const struct flash_ccu_read_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ccu_read_res_unpack(
    struct flash_ccu_read_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_read_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_read_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_read_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ccu_read_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_read_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_read_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_erase_req_pack(
    uint8_t *dst_p,
    const struct flash_ccu_erase_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ccu_erase_req_unpack(
    struct flash_ccu_erase_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_erase_req_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_erase_req_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_erase_req_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ccu_erase_res_pack(
    uint8_t *dst_p,
    const struct flash_ccu_erase_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ccu_erase_res_unpack(
    struct flash_ccu_erase_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ccu_erase_res_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ccu_erase_res_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ccu_erase_res_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_status_pack(
    uint8_t *dst_p,
    const struct flash_dbu_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->status, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->status, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->status, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->status, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->status, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->status, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->status, 56u, 0xffu);

    return (8);
}

int flash_dbu_status_unpack(
    struct flash_dbu_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t flash_dbu_status_status_encode(double value)
{
    return (uint64_t)(value);
}

double flash_dbu_status_status_decode(uint64_t value)
{
    return ((double)value);
}

bool flash_dbu_status_status_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_write_req_pack(
    uint8_t *dst_p,
    const struct flash_dbu_write_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dbu_write_req_unpack(
    struct flash_dbu_write_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_write_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_write_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_write_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dbu_write_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_write_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_write_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_write_res_pack(
    uint8_t *dst_p,
    const struct flash_dbu_write_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dbu_write_res_unpack(
    struct flash_dbu_write_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_write_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_write_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_write_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dbu_write_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_write_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_write_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_read_req_pack(
    uint8_t *dst_p,
    const struct flash_dbu_read_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dbu_read_req_unpack(
    struct flash_dbu_read_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_read_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_read_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_read_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dbu_read_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_read_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_read_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_read_res_pack(
    uint8_t *dst_p,
    const struct flash_dbu_read_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_dbu_read_res_unpack(
    struct flash_dbu_read_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_read_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_read_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_read_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_dbu_read_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_read_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_read_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_erase_req_pack(
    uint8_t *dst_p,
    const struct flash_dbu_erase_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_dbu_erase_req_unpack(
    struct flash_dbu_erase_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_erase_req_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_erase_req_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_erase_req_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_dbu_erase_res_pack(
    uint8_t *dst_p,
    const struct flash_dbu_erase_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_dbu_erase_res_unpack(
    struct flash_dbu_erase_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_dbu_erase_res_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_dbu_erase_res_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_dbu_erase_res_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_status_pack(
    uint8_t *dst_p,
    const struct flash_ams_status_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u64(src_p->status, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u64(src_p->status, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u64(src_p->status, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u64(src_p->status, 24u, 0xffu);
    dst_p[4] |= pack_right_shift_u64(src_p->status, 32u, 0xffu);
    dst_p[5] |= pack_right_shift_u64(src_p->status, 40u, 0xffu);
    dst_p[6] |= pack_right_shift_u64(src_p->status, 48u, 0xffu);
    dst_p[7] |= pack_right_shift_u64(src_p->status, 56u, 0xffu);

    return (8);
}

int flash_ams_status_unpack(
    struct flash_ams_status_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->status = unpack_right_shift_u64(src_p[0], 0u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[1], 8u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[2], 16u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[3], 24u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[4], 32u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[5], 40u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[6], 48u, 0xffu);
    dst_p->status |= unpack_left_shift_u64(src_p[7], 56u, 0xffu);

    return (0);
}

uint64_t flash_ams_status_status_encode(double value)
{
    return (uint64_t)(value);
}

double flash_ams_status_status_decode(uint64_t value)
{
    return ((double)value);
}

bool flash_ams_status_status_is_in_range(uint64_t value)
{
    (void)value;

    return (true);
}

int flash_ams_write_req_pack(
    uint8_t *dst_p,
    const struct flash_ams_write_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ams_write_req_unpack(
    struct flash_ams_write_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_write_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_write_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_write_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ams_write_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_write_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_write_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_write_res_pack(
    uint8_t *dst_p,
    const struct flash_ams_write_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ams_write_res_unpack(
    struct flash_ams_write_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_write_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_write_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_write_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ams_write_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_write_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_write_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_read_req_pack(
    uint8_t *dst_p,
    const struct flash_ams_read_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ams_read_req_unpack(
    struct flash_ams_read_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_read_req_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_read_req_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_read_req_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ams_read_req_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_read_req_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_read_req_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_read_res_pack(
    uint8_t *dst_p,
    const struct flash_ams_read_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->address, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->address, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->address, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->address, 24u, 0xffu);
    dst_p[4] |= pack_left_shift_u32(src_p->word, 0u, 0xffu);
    dst_p[5] |= pack_right_shift_u32(src_p->word, 8u, 0xffu);
    dst_p[6] |= pack_right_shift_u32(src_p->word, 16u, 0xffu);
    dst_p[7] |= pack_right_shift_u32(src_p->word, 24u, 0xffu);

    return (8);
}

int flash_ams_read_res_unpack(
    struct flash_ams_read_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->address = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->address |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);
    dst_p->word = unpack_right_shift_u32(src_p[4], 0u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[5], 8u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[6], 16u, 0xffu);
    dst_p->word |= unpack_left_shift_u32(src_p[7], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_read_res_address_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_read_res_address_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_read_res_address_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

uint32_t flash_ams_read_res_word_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_read_res_word_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_read_res_word_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_erase_req_pack(
    uint8_t *dst_p,
    const struct flash_ams_erase_req_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ams_erase_req_unpack(
    struct flash_ams_erase_req_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_erase_req_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_erase_req_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_erase_req_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}

int flash_ams_erase_res_pack(
    uint8_t *dst_p,
    const struct flash_ams_erase_res_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    memset(&dst_p[0], 0, 8);

    dst_p[0] |= pack_left_shift_u32(src_p->erase_all, 0u, 0xffu);
    dst_p[1] |= pack_right_shift_u32(src_p->erase_all, 8u, 0xffu);
    dst_p[2] |= pack_right_shift_u32(src_p->erase_all, 16u, 0xffu);
    dst_p[3] |= pack_right_shift_u32(src_p->erase_all, 24u, 0xffu);

    return (8);
}

int flash_ams_erase_res_unpack(
    struct flash_ams_erase_res_t *dst_p,
    const uint8_t *src_p,
    size_t size)
{
    if (size < 8u) {
        return (-EINVAL);
    }

    dst_p->erase_all = unpack_right_shift_u32(src_p[0], 0u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[1], 8u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[2], 16u, 0xffu);
    dst_p->erase_all |= unpack_left_shift_u32(src_p[3], 24u, 0xffu);

    return (0);
}

uint32_t flash_ams_erase_res_erase_all_encode(double value)
{
    return (uint32_t)(value);
}

double flash_ams_erase_res_erase_all_decode(uint32_t value)
{
    return ((double)value);
}

bool flash_ams_erase_res_erase_all_is_in_range(uint32_t value)
{
    (void)value;

    return (true);
}
